update for mithril 2
flarum/statistics pull request #12
Opened 2020-08-16 05:07 UTC by askvortsov1

2020-08-16 18:28 UTC, clarkwinkelmann reviewed
Since we're inside a class component and `drawChart` is bound to `this`, can't we just replace `vnode.state.chart` with `this.chart` ?

2020-08-20 14:29 UTC, dsevillamartin requested changes

2020-08-20 14:29 UTC, datitisev commented on js/src/admin/components/StatisticsWidget.js
> +          label += ' - ' + dayjs.unix(i + offset + period.step - 1).utc().format('D MMM');
You didn't remove the `.utc()` call here.

2020-08-24 21:49 UTC, clarkwinkelmann approved these changes
Seems good visually. I expect you have tested locally that may suggested changes are actually working? :innocent: 

I didn't know we could use `oncreate`/`onupdate` outside of components. We could also do those tasks methods on the Component's `oncreate`/`onupdate`. Right now I think it might be a bit confusing since `this` is the state of `StatisticsWidget` while `vnode` is a reference to the `.StatisticsWidget-chart` child element :thinking:

2020-08-24 21:51 UTC, askvortsov1 commented
I have. And iirc, mithril treats vnode with life cycle hooks as components?

2020-08-24 22:04 UTC, clarkwinkelmann commented
If it works, I'm fine with the current approach. We can always revisit this at a later time if we decide to avoid this kind of lifecycle hooks.

2020-08-28 13:53 UTC, franzliedke commented
Yeah, it would probably be less surprising when extracted to its own component / fragment. Let's add it to the long list of "nice to haves". :wink:

2020-08-28 16:15 UTC, franzliedke commented
I extracted the moment -> dayjs changes to master.

2020-08-28 16:15 UTC, franzliedke approved these changes

2020-09-24 02:55 UTC, merged